apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
  - image: pythonmstpl
deploy:
  helm:
    releases:
    - name: pythonmstpl
      chartPath: helm
      artifactOverrides:
        image: pythonmstpl
      imageStrategy:
        helm: {}

