apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.resources.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 5000
          failureThreshold: 1
          periodSeconds: 30
        resources:
          requests:
            memory: {{ .Values.resources.resourcesRequests.memory }}
            cpu: {{ .Values.resources.resourcesRequests.cpu }}
          limits:
            memory: {{ .Values.resources.resourcesLimits.memory }}
            cpu: {{ .Values.resources.resourcesLimits.cpu }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
