apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.resources.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 5000
          failureThreshold: 1
          periodSeconds: 30
        resources:
          requests:
            memory: {{ .Values.resources.resourcesRequests.memory }}
            cpu: {{ .Values.resources.resourcesRequests.cpu }}
          limits:
            memory: {{ .Values.resources.resourcesLimits.memory }}
            cpu: {{ .Values.resources.resourcesLimits.cpu }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-config
