name: pythonmstpl
image:
  repo: pythonmstpl
  tag: 1.0.0
resources:
  replicaCount: 1
  resourcesLimits:
    memory: 1024Mi
    cpu: 2
  resourcesRequests:
    memory: 512Mi
    cpu: 1
config:
  environment: "dev"
